### PR TITLE
Bug 1120828 - Outputting statistics at the end of each suite test

### PR DESCRIPTION
**Pull request by eliperelman**

### CODE REVIEW

**Comment by rwood-moz** [comment]
If RUNS < 10 then p95 is "NaN'". When I do RUNS=30, a value appears for p95. Does stats.percentile require a minimum number of values? Or is this a conversion problem or something...

**Comment by eliperelman** [comment]
I ran into the same scenario. I think standard deviation and p95 need a certain amount of data before it can produce meaningful output.

**Comment by rwood-moz** [comment]
Ok, yeah that does make sense. If you're fine with "NaN" fine with me, although maybe something like "n/a" would be better or "do more runs" haha

**Comment by eliperelman** [comment]
:smile: OK, lemme see what I can come up with.

**Pull request merged**
